### ISSUE TITLE
Source code release

### ISSUE THREAD

**Issue by zoe2718** [zhengyuf/IMavatar#1]
Thank you for your amazing job. When are you going to release the source code?

**Comment by zhengyuf** [comment]
Hey,

Thank you for your interest in our work!
The code still needs some cleaning and I'm planning to release the code in late May or early June. 
Hope for your understanding 🙏  and I'm happy to discuss if you have questions regarding specific modules that are described in our paper. 

Best,
Yufeng

**Comment by Jianf-Wang** [comment]
Hi, I noticed that you used DECA to get pose matrix, but DECA seems to return [scale, tx, ty], instead of [tz, tx, ty]. How do you get the translation vector from DECA ? Could you please give more details about how you get the transformation matrix with DECA (similar to those in NerFace) ?

**Comment by zhengyuf** [comment]
Hey there,

Sorry for the late reply.
I actually didn't use the DECA camera pose parameters and only used its FLAME parameters. I initialized the camera to be located at [0, 0, -tz] and facing towards the origin point. 
Then I optimized the camera translation parameters along with the FLAME parameters using 2D keypoint projection loss. 
Hope that explained it.

Best,
Yufeng

**Comment by zhengyuf** [comment]
Of course, I will also release the code for preprocessing. 
It's a standard face tracking pipeline that uses DECA as initialization and refines parameters with 2D keypoint projection loss, temporal smoothness loss, and expression/shape regularization loss. 
It's probably not the best face tracker but works OKish and matches the expected input format of the IMavatar code.

**Comment by Jianf-Wang** [comment]
Ok, thanks for your reply. Looking forward to your code release :)

**Comment by buaaswf** [comment]
Ok, thanks for your reply. Looking forward to your code release :)

**Comment by Jianf-Wang** [comment]
Hi, could you please give more details about your temporal smoothness loss (mathematic formulation) ?

**Comment by ivernaloo** [comment]
are there any update?

**Comment by zhengyuf** [comment]
coming real soon!
