### ISSUE TITLE
FLAMEServer.inverse_skinning_pts

### ISSUE THREAD

**Issue by UestcJay** [zhengyuf/IMavatar#10]
many thanks for your great work! In FLAMEServer.inverse_skinning_pts, I do not understand the meaning of pnts_c_original, why should forward_skinning_pts after getting pnts_c_original?
Thanks for your time!

**Comment by zhengyuf** [comment]
Hey,

Thank you for your question. 
The FLAME canonical space has the mouth closed, but this results in a sharp transition in LBS weight between the lips, which cannot be learned by a continuous deformer MLP.
Therefore, we used a different canonical space from FLAME, by setting the canonical pose to a [mouth-opened state](https://github.com/zhengyuf/IMavatar/blob/98de8e2b18bc992eb79d7fadaedbe8bfed513f79/code/flame/FLAME.py#L68). 
So to answer your question, `pnts_c_original` is in the FLAME canonical space, we then map it to the IMavatar canonical space. 

Best,
Yufeng

**Comment by UestcJay** [comment]
thanks for your reply!
