### ISSUE TITLE
coordinate system 

### ISSUE THREAD

**Issue by UestcJay** [zhengyuf/IMavatar#11]
hi, yufeng
     In `get_camera_params`  functions, the z  is mul -1,  I wonder if the camera and world coordinate system follow the OpenCV convention[right, down, forward]?

**Comment by zhengyuf** [comment]
Hey,

It probably doesn't follow OpenCV convention.
The z is not forward, but backward. x and y are probably right and down, but I'm not sure...
I just found a way that worked and I don't dare changing the camera system anymore.😂

Best,
Yufeng

**Comment by UestcJay** [comment]
thanks for your reply! sorry to bother you again. why the `fx` mul -1 in  optimize.py [here](https://github.com/zhengyuf/IMavatar/blob/98de8e2b18bc992eb79d7fadaedbe8bfed513f79/preprocess/DECA/optimize.py#L64)

**Comment by zhengyuf** [comment]
It's also multiplied by -1 in the [saved intrinsics](https://github.com/zhengyuf/IMavatar/blob/98de8e2b18bc992eb79d7fadaedbe8bfed513f79/preprocess/DECA/optimize.py#L156), so we made sure that the main code and preprocessing code have the same camera transformations.

As for why, there is not really a good reason, I think I just followed NerFace which also multiplied fx with -1, and just kept using this.
