### ISSUE TITLE
Training problem

### ISSUE THREAD

**Issue by 541979210** [zhengyuf/IMavatar#12]
I would like to know if the epoch setting parameter must be 1000. I have a result for training almost 60 epochs, and it seems to get a poor texture/geometry. With my V100 gpu, it takes 1 day to train 60 epochs, seems unusual. So I want to know how to speed up training process? 
Thanks for your time.

**Comment by zhengyuf** [comment]
Hey,

No, I only train for about 60 epochs with `batch_size = 1` x `num_sample = 2048` or around 300 epochs with `batch_size = 8` x `num_sample = 256`. 
Could you download the pretrained model to check whether your result matches that? It has the result visualization for epochs 0 - 70 (`batch_size = 1` x `num_sample = 2048`)
If your model doesn't match this quality, please send your result. Thanks.

Best,
Yufeng
