### ISSUE TITLE
Rig the Implicit Model

### ISSUE THREAD

**Issue by SuperStacie** [zhengyuf/IMavatar#15]
Hi,

Thanks for the very interesting work. I have a couple questions about the work.
I just wonder if the script can be provided about how to rig the generated head mesh on real dataset by customized expression and pose parameters within the range.
Can the generated mesh be improved? It seems to have ray-marching step size artifacts on the surface and the messy parts down below the neck.
I notice the inference time is very long, like 15s per frame for only model output (not included plot time), is it simply due to the iterative root-finding process?

Thanks!

**Comment by zhengyuf** [comment]
Hi,

- I didn't plan to release the script for generating rigged mesh, but I can add it to my todo list. However, pls don't wait for it.
- You can change the `res_init` and `res_up` in the .conf file to eliminate the marching cube artifacts, but then it will be slower. You can also probably regularize the invisible surfaces (for e.g., below the neck) by designing and adding some simple losses. 
-The speed is limited by both iterative root finding and ray marching. There are many ways to improve, for example, by disgarding samples which are far away from the FLAME surface. But we are not planning to add these to the code. 

Yufeng
