### ISSUE TITLE
The size of the output mesh is too small

### ISSUE THREAD

**Issue by 1208869644** [zhengyuf/IMavatar#18]
thank you for your great work，by using the unsupervised pretrained model, the output mesh is only 2.4M. Is there any way to improve the output mesh?

**Comment by zhengyuf** [comment]
You can change the res_init and res_up in the .conf file to eliminate the marching cube artifacts, but then it will be slower.

**Comment by Zvyozdo4ka** [comment]
@1208869644 how did you get mesh?

@zhengyuf is it possible to get point cloud?
