### ISSUE TITLE
_pygit2.GitError: Repository not found at 

### ISSUE THREAD

**Issue by yangdaowu** [zhengyuf/IMavatar#19]
Hello, I have encountered such a problem. How should I solve it.

![image](https://user-images.githubusercontent.com/64669901/179702006-8c4d86de-79ef-4d2b-88e0-633c34a89649.png)

**Comment by OvOtoQAQ** [comment]
hi, I have a same problem, the "_pygit2.GitError: Repository not found at ." one, have you solved it? Could you please tell me how? Thanks in advance:)
