### ISSUE TITLE
Video

### ISSUE THREAD

**Issue by yangdaowu** [zhengyuf/IMavatar#21]
Hello, I haven't found the video you used in your paper. Can you provide it to me, thank you.

![image](https://user-images.githubusercontent.com/64669901/182994117-440d10f9-8049-47ce-8de7-1bb499234237.png)

**Comment by zhengyuf** [comment]
This is already released. Please check download_data.bash

**Comment by readilychen** [comment]
MVI_1810.MOV  MVI_1811.MOV  MVI_1812.MOV  MVI_1814.MOV
didn't found these files in yufeng.zip .   is it the right place?


yufeng/yufeng# ls
MVI_1810  MVI_1811  MVI_1812  MVI_1814
