### ISSUE TITLE
RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn

### ISSUE THREAD

**Issue by OvOtoQAQ** [zhengyuf/IMavatar#23]
Dear yufeng, thanks for your excellent work!

I have an issue as in title which seems because of these lines in ``` loss.py```
```
if (network_object_mask & object_mask).sum() == 0:
            return torch.tensor(0.0).cuda().float() 
```
Usually everything goes well before 70 epochs on your dataset, but will suddenly collapse around about 80 epochs, and on my own dataset collected by kinect it always collapses within 20 epochs sometimes 5 and I totally follow your head motion and expression when I shot videos.

I notice you mention that your model is sensitive to 3DMM parameters, is my problem due to noise in parameters? and how do you solve this problem on a totally new dataset? Do I need to finetune face tracking model on my dataset?

Please tell me more details, thanks in advance! And thanks for releasing your excellent code again!

**Comment by zhengyuf** [comment]
Hey,

First of all, sorry for the instability of the code. I also experienced training collapse after convergence.

If training never converges, it could be that the preprocessing hyperparameters need to be tuned. For e.g., if FPS is lower, then the smoothing loss weights should probably also be lower. You can check this by rendering the tracked FLAME model and see whether it's following the video.

Other things that make it hard: Shadows, motion blur, and wrong intrinsics.

Good luck with debugging ✊

best,
Yufeng

**Comment by ForrestPi** [comment]
@OvOtoQAQ Hi, have you sloved the problem?  I met the same problem when running the sample data

**Comment by zhangqianhui** [comment]
@ForrestPi @zhengyuf @OvOtoQAQ  hi, guys, I also encountered the same problem even if using original yufeng's data.
