### ISSUE TITLE
Training diverged after a few epoch

### ISSUE THREAD

**Issue by sallyc-flwls** [zhengyuf/IMavatar#27]
Hi Yufeng, 

Thanks so much for the great work! I have been trying training with the conf file you provided and on the provided dataset, however it seems the training diverged after 3 epochs for supervised training on folders [MVI_1810, MVI1814] and unsupervised training on folders [MVI_1810, MVI1811] (I have not tried any other experiment ). I'm training on Nvidia A10G.

Here are the evaluation results for supervised training on folders [MVI_1810, MVI1814]:
epoch 2
![image](https://user-images.githubusercontent.com/105666189/192124454-6ee3d5e9-3ec9-456f-bfcb-3a2cd3e01f4e.png)
epoch 3
![image](https://user-images.githubusercontent.com/105666189/192124461-fe1344bf-215e-4758-93a3-92197bfeb8fe.png)

Evaluation results for unsupervised training on folders [MVI_1810, MVI1811]:
epoch 25
![image](https://user-images.githubusercontent.com/105666189/192124523-424c0128-424f-4c71-9081-197a807124dd.png)
epoch 30
![image](https://user-images.githubusercontent.com/105666189/192124533-3102fe77-aaa2-424f-8a1e-0428245008e4.png)
epoch 35
![image](https://user-images.githubusercontent.com/105666189/192124542-2ccf0fbc-3d3d-4e61-9a72-5c812cc61594.png)

I was wondering if you have encountered such issue before? Thanks a lot for your help! 

Sally

**Comment by zhengyuf** [comment]
Hey Sally,

The problem is probably the GPU model. IMavatar's result on A100 is similar to this. The instability comes from the Broyden's method, and perhaps also the ray marching secant method.
Could you try using a GeForce RTX2080Ti or Quadro RTX6000? I tried with these two and they work.

Yufeng

**Comment by sallyc-flwls** [comment]
Hi Yufeng, 

Thanks a lot for your reply. Sounds good, will try out on RTX2080Ti!

Sally
