### ISSUE TITLE
About the evaluation metrics of IMavatar

### ISSUE THREAD

**Issue by zliucz** [zhengyuf/IMavatar#30]
Hi yufeng,
Your work IMavatar is brilliant 🙂. I re-run your work IMavatar on RTX2080Ti. However, the results of my run and your given pre-trained model seem inconsistent with your paper. Attached is part of my results. I think it is because we use different evaluation metrics codes. My metrics are modified from NerFACE. Would you please share your implementation code of evaluation metrics? 
![image](https://user-images.githubusercontent.com/64915812/192991177-f9db9f1e-71a6-4ca4-9614-f3ed368780c5.png)

Thanks a lot,
Zichen

**Comment by zhengyuf** [comment]
Hey Zichen,

Thanks for the kind words!
I've cleaned the metric file and added it as ./code/utils/calculate_metrics.py. I know I've already replied to your email but just replying so that I can close this issue :)

Best,
Yufeng
