### ISSUE TITLE
_pygit2.GitError: Repository not found at .

### ISSUE THREAD

**Issue by Icelame-31** [zhengyuf/IMavatar#31]
Traceback (most recent call last):
  File "scripts/exp_runner.py", line 36, in <module>
    wandb_workspace=opt.wandb_workspace,
  File "../code/scripts/train.py", line 84, in __init__
    + str(pygit2.Repository('IMavatar').head.target) + '\n') # commit hash)
  File "/root/miniconda3/envs/a/lib/python3.7/site-packages/pygit2/repository.py", line 1620, in __init__
    path_backend = init_file_backend(path, flags)
_pygit2.GitError: Repository not found at .

can you help me with this error , thank you very much.

**Comment by zhengyuf** [comment]
Simply comment the line out. It logs which git commit the current experiment is at, only useful for developing.

**Comment by Icelame-31** [comment]
I have solved this prolblem, thank you very much for you reply.







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zhengyuf/IMavatar"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年10月28日(星期五) 下午5:54
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [zhengyuf/IMavatar] _pygit2.GitError: Repository not found at . (Issue #31)





 
Simply comment the line out. It logs which git commit the current experiment is at, only useful for developing.

**Comment by phoenix8875** [comment]
@zhengyuf @Icelame-31 Can you please elaborate on which line to comment in which file , I am a beginner
