### ISSUE TITLE
Path To Pretrained models

### ISSUE THREAD

**Issue by RAJA-PARIKSHAT** [zhengyuf/IMavatar#32]
I download the preprocessed dataset, along with which I think pretrained models are also downloaded. Where the pretrained models are downloaded. @zhengyuf 

Secondly, can I get a 3D model as an output, I am doing my research project and the target is to use a video of a specific identity to generate a 3D model (train) and then input any new image to get the 3D model of the same identity. Can I do this with this project?

**Comment by zhengyuf** [comment]
Hey,

Pre-trained models are downloaded to ./data/experiments
Yeah, you can do this task with this repo. Again, please follow the instructions in readme and ./preprocessing/readme.

Yufeng
