### ISSUE TITLE
Supervised vs. Unsupervised

### ISSUE THREAD

**Issue by TouqeerAhmad** [zhengyuf/IMavatar#33]
Hi @zhengyuf, I am trying to run IMavatar pipeline and possibly on my on data. As a first step I have I have dowloaded the processed data and the checkpoints as described in 

https://github.com/zhengyuf/IMavatar/blob/main/download_data.bash

and then tried running the eval code as advised: 

`python scripts/exp_runner.py --conf ./confs/IMavatar_supervised.conf --is_eval`

However, the checkpoints downloaded from the link in download_data.bash contains 'IMavatar_unsupervised', while the code (test.py in the scripts) expects it to be 'IMavatar'. Once I changed the directory from IMavatar_unsupervised to IMavatar, was able to run the test.py without complains. Is that a mistake i.e., link is wrong in download_data.bash or the directory name is just wrong and what I did is fine? 

Thanks, 
Touqeer

**Comment by xmlyqing00** [comment]
I have the same problem and changed the directory name as you did.

I found the inferred geometry is wired. Do you have any ideas about it?

Thanks,
Yongqing

![image](https://user-images.githubusercontent.com/8945602/202581332-42dd4f31-d5b9-4060-883e-ff1e4fdb5e5b.png)

**Comment by yangqing-yq** [comment]
same preview issue for the pretrained model

**Comment by zhengyuf** [comment]
This is simply because the released model is trained with the unsupervised setting. If you use the IMavatar_unsupervised.conf instead of IMavatar_supervised.conf, everything will work fine. 
We didn't release the supervised model.

**Comment by zhengyuf** [comment]
As for the previewed geometry, the unseen geometry can be random as there is no regularization. In this case, it shows some periodic effects, this is perhaps due to some unknown inductive biases of MLPs.
