### ISSUE TITLE
how to download the synthetic dataset for evaluation?

### ISSUE THREAD

**Issue by yangqing-yq** [zhengyuf/IMavatar#35]
hi @zhengyuf 
Regarding the paper chapter 4.1, it mentioned 'We release the synthetic dataset for research purposes.' I would like to know if this is already released and where could I access it?

thanks,
yq

**Comment by zhengyuf** [comment]
Hey yq,

it's here: https://dataset.ait.ethz.ch/downloads/imaOsdfvRe/

but the camera format is a bit different than the real dataset (If I remembered correctly, z axis need to be inverted).

best,
Yufeng

**Comment by yangqing-yq** [comment]
thanks @zhengyuf
Your reply is really helpful! I will check it out.
