### ISSUE TITLE
About resolution

### ISSUE THREAD

**Issue by HyunsooCha** [zhengyuf/IMavatar#36]
Hi,

Thank you for your excellent work!
I would like to ask you if there are any 512 by 512 input-specific settings in IMavatar. I would like to change the input resolution, not 512 by 512. I changed the training ray casting sampling rate (2048 to other) and intrinsic parameters. Is there something I missed? 
Plus, what if I changed the hidden dimension of the deformation network 512 to 256? Why is the hidden dimension 512?
In the 'IMavatar_supervised.conf' file, the dataset's img_res was [256, 256]. However, MVI_1810's image resolution is 512 by 512. So do we have to change the conf file [256, 256] to [512, 512]?

Thank you :)

**Comment by HyunsooCha** [comment]
I solved the questions on my own. 

Closed.

**Comment by pinakinathc** [comment]
@HyunsooCha hi -- I also tried to use 512x512 resolution -- but I guess I M Avatar works on 20XX Ti GPUs (8GB VRAM).
Can you tell me your GPU and config where 512x512 resolution works?

**Comment by HyunsooCha** [comment]
@pinakinathc Hey,

I modified the code for RTX 3090, which means that I warped the IMAvatar code for multiGPU parallelization.
