### ISSUE TITLE
Cross-subject Reenactment

### ISSUE THREAD

**Issue by uniBruce** [zhengyuf/IMavatar#40]
Hi, thanks for the amazing work. I am still wondering how to achieve cross-subject reenactment after reading the README file. Could you please provide some instructions?

**Comment by zhengyuf** [comment]
Hey,

For cross-subject reenactment, you can move the json file of the test sequence into the training subject's folder (under the same structure), and then change trained avatar's config file by replacing `dataset.test.subdir` to the test sequence's name. Set `--only_json True` to disable the loading of GT images and run inference.

Yufeng

**Comment by uniBruce** [comment]
> Hey,
> 
> For cross-subject reenactment, you can move the json file of the test sequence into the training subject's folder (under the same structure), and then change trained avatar's config file by replacing `dataset.test.subdir` to the test sequence's name. Set `--only_json True` to disable the loading of GT images and run inference.
> 
> Yufeng

Thanks for your reply. I am trying to perform cross-subject experiments, but the inference speed seems very slow (160~280s per frame). Is that normal? Or could I omit some unnecessary operations to accelerate the testing? Btw, I just need the RGB outputs.
<img width="468" alt="b0faa4e754e72feea62fb26c6791f267" src="https://user-images.githubusercontent.com/31914632/233022401-07239650-76cd-43ce-8d4f-27d245c98161.png">

**Comment by zhengyuf** [comment]
Hi,

I don't think there is an easy way to speed inference up, except by reducing the resolution which speeds it up quadratically.

One way to speed up, is to extract the canonical mesh, the blendshapes and skinning weights, and render IMavatar as a rigged mesh. But the mesh normals will be slightly different and therefore the rendering would also be slightly different. 

I didn't implement this in the released code though, so I would suggest to just wait for it if you are not in a hurry 

Yufeng

**Comment by uniBruce** [comment]
Thanks a lot for your reply!
