### ISSUE TITLE
How to use hash encoder to make it fast?

### ISSUE THREAD

**Issue by YiChenCityU** [zhengyuf/IMavatar#41]
Hi, I wonder would it possible to use hash ecoding to acclerate the code. But I found the the gradient           https://github.com/zhengyuf/IMavatar/blob/b7d11d891e807a9d21ffd50eb4d596d63a249e71/code/model/implicit_morphable_model.py#L331 always failed. Could you give some advices?

**Comment by zhengyuf** [comment]
Is this issue still open? If so, please feel free to reopen and provide more details.
