### ISSUE TITLE
help! pip to install libgcc-ng failed in windows

### ISSUE THREAD

**Issue by Dragonkingpan** [zhengyuf/IMavatar#42]
Thank you very much for your masterpiece. I am a **Windows** user and I have the following problem when installing the environment: I use：
` pip to install libgcc-ng=9.3.0`
but I cannot install it, and the error is returned: 
```
ERROR: Could not find a version that satisfies the requirement libgcc-ng==9.3.0 (from versions: none)
ERROR: No matching distribution found for libgcc-ng==9.3.0。
```
 Since I'm new to python and I don't know how to fix this, can you help me ? thanks

**Comment by zhengyuf** [comment]
Hey, I'm sorry but I don't have a windows computer and have never tried to run this code on a windows machine..
