### ISSUE TITLE
How to make sure that the "world coordinate" of different videos consistent？

### ISSUE THREAD

**Issue by zydmu123** [zhengyuf/IMavatar#44]
According to the optimization in the preprocessing, there are different extrinsicses correspond to different videos such as MVI_1810 and MVI_1814, I wonder whether the world coordinate is consistent to all the videos. As different videos are trained together, it's very important for maintaining consistency in different view directions!

**Comment by rohit7044** [comment]
Hey did you solve this? If yes, can you explain how?
