### ISSUE TITLE
Update Nov 7 released dataset google drive

### ISSUE THREAD

**Issue by bbakpil** [zhengyuf/IMavatar#46]
Thanks for your awesome work.

I've chekced your new released dataset google drive link, and found a file "transforms_tran.json"

<img width="609" alt="Screenshot 2023-10-18 at 7 55 17 PM" src="https://github.com/zhengyuf/IMavatar/assets/144920495/c50460e6-47be-49bc-8716-14ade6c6a756">

This file was not included in the original dataset, and I it seems that the content of the file follows (maybe) NeRF-formatted dataset.

What is the purpose of "transforms_tran.json"?

**Comment by zhengyuf** [comment]
Hi, 

yes this is the converted parameters for running NerFace. Since a lot of people seems to have trouble with the conversion, I put it there for convenience. It's not used for IMavatar.
