### ISSUE TITLE
Questions about get_differentiable_non_surface() and get_differentiable_x()

### ISSUE THREAD

**Issue by haonanhe** [zhengyuf/IMavatar#47]
In the file `./code/model/implicit_morphable_model.py, line 128 and 145,` functions `get_differentiable_non_surface()` and `get_differentiable_x()` are used. I don't really understand their functions here. I would appreciate it if you could explain this to me. It would be really helpful. Thank you so much.

**Comment by zhengyuf** [comment]
Hi,

This is the part where we get analytical gradient for points that are on the surface and not on the surface. 
You can also check sec 3.3 and equation 8, 9 and 10 for details on this.

**Comment by haonanhe** [comment]
Thank you for your explanation. That's really helpful.
