### ISSUE TITLE
restruction of the hair

### ISSUE THREAD

**Issue by Jiatttliu** [zhengyuf/IMavatar#49]
Hi,Yufeng!This is groundbreaking work, but I have a question: how do you reconstruct parts of the flame model that are not included in the reconstruction process, including the hair?Can you get back to me if you are free?
best wish

**Comment by zhengyuf** [comment]
hi,

IMavatar's geometry is not limited by the FLAME model. We only leverage FLAME's deformation scheme (blendshape + LBS). Therefore, as long as the hair does not have non-rigid deformation that cannot be explained by the head transformation, the method will work fine.
