### ISSUE TITLE
About camera intrinsics

### ISSUE THREAD

**Issue by junhahyung** [zhengyuf/IMavatar#5]
Thank you for your great work.

I am new to this domain, and I'm having trouble getting camera intrinsics(f_x, f_y, c_x, c_y).
Can you share your experience with recording the videos and getting the intrinsics?

Specifically,
I am trying to use iPhone12pro to collect the videos myself, and used ios app called vizario to get instrinsics, but there are 3 cameras on the iPhone, so I'm not sure I've got the correct one.
Also c_x, and c_y can change after cropping. How do you deal with this?

Thanks

**Comment by zhengyuf** [comment]
Hey,

Thank you for your interest in our work.

We used a checkerboard to calibrate our DSLR cameras. Using mobile phones will work to some extent but I think there might be focal-length changes and/or auto-enhancement during the capture. 

As for c_x and c_y values after cropping. Leveraging the fact that the principal point doesn't change with cropping, you can calculate the updated values. I calculated them by hand.

best,
Yufeng

**Comment by junhahyung** [comment]
Thank you so much :)
