### ISSUE TITLE
May I ask about  what do the pose in the the code. json and flame_params.json file represent

### ISSUE THREAD

**Issue by wuzuyin** [zhengyuf/IMavatar#50]

**Comment by zhengyuf** [comment]
Hi,

FLAME parameters consist of 50/100 expression parameters, and 15 pose parameters. The pose parameters control the rotation transformation of the head, jaw and eyes.

**Comment by RayShing** [comment]
> FLAME parameters consist of 50/100 expression parameters, and 15 pose parameters. The pose parameters control the rotation transformation of the head, jaw and eyes.

Hi, I would like to ask a question regarding pose parameters. Based on the DECA paper, the pose parameters of FLAME should be 15: "pose 𝜽 ∈ R 3𝑘+3 (with 𝑘 = 4 joints for neck, jaw, and eyeballs)". I notice that the FLAME pose parameters you provided also contain 15 dimensions. However, when I run DECA, somehow I can only get 6 dimensions for pose. Could you instruct me how to get 15-dimension pose parameters from DECA? Also, another question I have is what is the meaning of "+3" in the pose parameters? Where does this additional 3 dimensions come from? 

![image](https://github.com/zhengyuf/IMavatar/assets/61814345/0b60e6fc-e279-4136-b470-8fbe4172c6f2)
