### ISSUE TITLE
May I ask why the dataset you provided is not divided into training and testing sets？

### ISSUE THREAD

**Issue by wuzuyin** [zhengyuf/IMavatar#53]

**Comment by zhengyuf** [comment]
For most of the works that used the provided datasets, I believe the train/test split is the following. 
Subject 1: 
  train: [MVI_1810, MVI_1814]
  test: [MVI_1812]
Subject 2:
  train:[MVI_1797, MVI_1801]
  test:[MVI_1802]

But as long as you use the same training and testing sequence for all compared methods, I think it shouldn't be a problem. For e.g., in IMavatar, we conduct experiments where we train with [MVI_1810, MVI_1811] and test with MVI_1812, to evaluate quality of out-of-distribution expressions.
