### ISSUE TITLE
coordinate system of IMavatar output

### ISSUE THREAD

**Issue by Zvyozdo4ka** [zhengyuf/IMavatar#55]
Is your project's output would be in the same coordinate system as FLAME?

**Comment by zhengyuf** [comment]
Yes. IMavatar's output is aligned with FLAME except for a scaling factor.

**Comment by Zvyozdo4ka** [comment]
@zhengyuf could you explain, please,

1. is it output? or input? i am so confused. Could you explain please what should be the input and what output will we get?
![image](https://github.com/zhengyuf/IMavatar/assets/74532816/d058cff9-aecf-4590-b50a-3bb3192fcc6f)

2. could give a hint how to get point cloud?

**Comment by zhengyuf** [comment]
1. I was assuming that the output is the reconstructed head SDF, and the input is the training video. 
2. You can either sample from the mesh, or directly use [PointAvatar](https://github.com/zhengyuf/PointAvatar)
