### ISSUE TITLE
Clarify the pipeline

### ISSUE THREAD

**Issue by longphamkhac** [zhengyuf/IMavatar#56]
Tks for your brilliant work!!! However, I want to clarify several steps in the proposed method. Specifically, first of all, the proposed method  extract the deformed points by utilizing FLAME, and then query the canonical points using correspondence seach, is that right ?

**Comment by zhengyuf** [comment]
Hi, 

the deformed points are not extracted from FLAME, they are instead sampled with ray marching, as in most implicit representation rendering methods. And yes the deformed points are then mapped to the canonical space using correspondence search. 

Yufeng

**Comment by zhengyuf** [comment]
feel free to re-open the issue
