### ISSUE TITLE
Analytical Gradient and its intuition

### ISSUE THREAD

**Issue by zhengyuf** [zhengyuf/IMavatar#6]
- **Analytical Gradient and its intuition**

We find the canonical ray-surface intersection x_c in an interactive manner. Our goal is to determine how the change of geometry and deformation affects the location of x_c, in other words, the gradient of x_c w.r.t the geometry and deformation network.

We leverage the fact that the final x_c **always** satisfies two constraints: it’s on the surface (occ (x_c) = 0.5) and its deformed location is on the ray  (P(x_d) = p). With any delta change of the geometry and deformation, the final location of x_c will change accordingly so that these two constraints still hold. Therefore, if we take the gradient of the constraints (rewrite as F(x_c) = 0) w.r.t the parameters of the geometry and deformation network, it will be equal to zero. Writing it into partial derivatives, we arrive at equation 10 in the main paper.
<img width="670" alt="image" src="https://user-images.githubusercontent.com/48751943/174501363-1a9623ac-7f64-4f41-9281-3e3cc35d98af.png">

**Comment by UestcJay** [comment]
> * **Analytical Gradient and its intuition**
> 
> We find the canonical ray-surface intersection x_c in an interactive manner. Our goal is to determine how the change of geometry and deformation affects the location of x_c, in other words, the gradient of x_c w.r.t the geometry and deformation network.
> 
> We leverage the fact that the final x_c **always** satisfies two constraints: it’s on the surface (occ (x_c) = 0.5) and its deformed location is on the ray (P(x_d) = p). With any delta change of the geometry and deformation, the final location of x_c will change accordingly so that these two constraints still hold. Therefore, if we take the gradient of the constraints (rewrite as F(x_c) = 0) w.r.t the parameters of the geometry and deformation network, it will be equal to zero. Writing it into partial derivatives, we arrive at equation 10 in the main paper. <img alt="image" width="670" src="https://user-images.githubusercontent.com/48751943/174501363-1a9623ac-7f64-4f41-9281-3e3cc35d98af.png">

Hi, Yufeng.  Why the constant is `deformed_x - points`  and not directly `deformed_x` [the line code ](https://github.com/zhengyuf/IMavatar/blob/a7c731d5cc17b6cfe959b9a3c44481335e8ba6c9/code/model/implicit_morphable_model.py#L317)

**Comment by zhengyuf** [comment]
Hey,

If you don't optimize the camera, then they are the same. But if you do, subtracting `points` allow you to back-propagate to ray directions and camera locations.

Best,
Yufeng
