### ISSUE TITLE
Missing saveCode in preprocess 

### ISSUE THREAD

**Issue by Nuyoah13** [zhengyuf/IMavatar#7]
Hi Yufeng,

Thanks for your excellent work.
I followed your preprocess steps to run on custom datas.  but find missing saveCode in the original DECA demo_reconstruction.py, which may generate code.json in your case.  Could you provide the complete code of demo_reconstruct.py? Thanks.

**Comment by Nuyoah13** [comment]
Solve, forgot to swap in some files in DECA, thanks.

**Comment by carlosedubarreto** [comment]
I was having the same problem. as I was using windows on the momento I had to sync the files from the preprocess and submodule, I made it the wrong way 😅

Thanks for this isse I solved this. Thanks @Nuyoah13
