### ISSUE TITLE
Flame Server scaling

### ISSUE THREAD

**Issue by ankarako** [zhengyuf/IMavatar#9]
Hi and thanks for sharing your great work!

I wanted to ask you something about the shape directions in your flame model implementation.
I understand that you scaled the model's template vertices and shape directionσ so the model can fit in a nearly unit bounding sphere.
However I noticed that when you [set the shape parameters](https://github.com/zhengyuf/IMavatar/blob/a7c731d5cc17b6cfe959b9a3c44481335e8ba6c9/code/flame/FLAME.py#L65) for identity at the model initialization you use the un-scaled shape directions with the scaled vertex template, and then during your `forward()` method you use the scaled shape directions for expression. Is there a specific reason for this?

Thanks for your time. :)

**Comment by zhengyuf** [comment]
Hey,

Thank you for pointing this out. It was a bug, now it's fixed!

Best,
Yufeng
